# Generated by Django 4.1.3 on 2023-01-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rohildb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npm', models.IntegerField(null=True)),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=255)),
                ('tetala', models.CharField(max_length=50)),
                ('kelas', models.CharField(max_length=50)),
            ],
        ),
    ]
